[project]
name = "fastrsf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "psutil>=7.0.0",
    "scikit-survival>=0.24.0",
]
